### ISSUE TITLE
Unicode characters break the security check

### ISSUE THREAD

**Issue by Thraka** [MichaCo/WebHookExample#1]
https://github.com/MichaCo/WebHookExample/blob/master/Website/Controllers/GitHookController.cs#L69

If the body contains a payload that has a unicode character, such as an issue comment using emoji's, the check will fail because a different hash will be created. If you use `var payloadBytes = Encoding.UTF8.GetBytes(payload);` you can fix this problem.

**Comment by MichaConrad** [comment]
Yup that's true. Depends on what you send. In that case, I didn't use unicode ;)

**Comment by Thraka** [comment]
I was testing with various comments made in the issue body on GitHub. The UTF8 parser still processes even if no unicode character exists. My initial test comment blob had a unicode character in it, though I didn't notice it, so I was fighting over and over trying to (i was using your blog post) figure out why the hashes weren't matching up.
